#!/bin/sh

ln -s /apps/usr/lib /usr/lib
ln -s /apps/usr/share/fonts /usr/share/fonts
ln -s /apps/usr/share/zoneinfo /usr/share/zoneinfo
mkdir -p /var/log/lighttpd
mkdir -p /var/lib/lighttpd/sockets

for file in /apps/bin/*
do
  ln -s $file /usr/bin/`basename $file`
done

for file in /apps/usr/bin/*
do
  ln -s $file /usr/bin/`basename $file`
done

for file in /apps/usr/sbin/*
do
  ln -s $file /usr/sbin/`basename $file`
done

for initscript in /apps/etc/init.d/S[0-9][0-9]*
do
        if [ -x $initscript ] ;
        then
                echo "[RCS]: $initscript"
                $initscript
        fi
done

exit 0
