#!/bin/sh

database=/data/configuration.sqlite3
tz_file=/etc/TZ

if [ -f $database ] ; then
  sqlcmd="select value from datetime where name='timezone'"
  tzname=$(sqlite3 "$database" "${sqlcmd}")
  timezone=$( \
    echo $tzname | \
    sed -r -e 's/^([a-zA-Z]+|<[^>]*>)([-]?[0-9:]+)/CST\2/g' \
           -e 's/DaylightTime/DST/g' \
  )
fi

echo ${timezone:-"CST-8"} > ${tz_file}
