#!/bin/sh

database=/data/configuration.sqlite3
tz_file=/etc/TZ

if [ -f $database ] ; then
  sqlcmd="select value from datetime where name='timezone'"
  tzname=$(sqlite3 "$database" "${sqlcmd}")
  sedexpr="s/(^<[^>]>|^[a-zA-Z]*)([+-:0-9]+).*/GMT\2/g"
  timezone=$(echo $tzname | sed -r -e "$sedexpr")
fi

echo ${timezone:-"GMT-8"} > ${tz_file}
