#!/bin/sh

ACTION_SCRIPT=/apps/etc/ifplugd/ifplugd.action

case "$1" in
  start)
    echo "Starting network"
    setuidgid root \
    ifplugd -I -i eth0 -r /apps/etc/ifplugd/ifplugd.action
    ifconfig lo 127.0.0.1
    ;;
  stop)
    echo "Shutting down network"
    ifplugd -k
    ;;
  restart)
    $0 stop
    usleep 200000
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

