#! /bin/sh

DATABASE=/data/configuration.sqlite3
NAME=ntpd
DAEMON=/usr/sbin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

case "$1" in
  start)
    echo -n "Starting $NAME: "
    use_ntp=$(sqlite3 $DATABASE \
        "select value from datetime where name='use_ntp'")
    ntp_server=$(sqlite3 $DATABASE \
        "select value from datetime where name='ntp_server'")
    if [ x"$use_ntp" = x"1" ]; then
      start-stop-daemon -S -q -x $DAEMON -- -d -p ${ntp_server:-pool.ntp.org}
      [ $? = 0 ] && echo "OK" || echo "FAIL"
    else
      echo "OK"
    fi
    ;;
  stop)
    echo -n "Stopping $NAME: "
    start-stop-daemon -K -q -n $NAME
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo -n "Restarting $NAME: "
    $0 stop > /dev/null 2>&1
    sleep 1
    $0 start > /dev/null 2>&1
    echo "OK"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
